import json

from bs4 import BeautifulSoup
from playwright.async_api import async_playwright


async def run_collection(company: str):

    # ----------------------------------------------------
    # Load the monitoring plan generated by Discovery.
    # ----------------------------------------------------

    with open(f"company_links/{company.lower()}.json", "r", encoding="utf-8") as file:

        monitoring_plan = json.load(file)

    # ----------------------------------------------------
    # Get all important pages.
    # ----------------------------------------------------

    important_pages = monitoring_plan["important_pages"]

    # ----------------------------------------------------
    # Launch Playwright once.
    # Reuse the same browser/page for every URL.
    # ----------------------------------------------------

    collected_pages = []

    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True)

        page = await browser.new_page()

        # ----------------------------------------------------
        # Visit every important page.
        # ----------------------------------------------------

        for page_info in important_pages:

            url = page_info["url"]
            category = page_info["category"]

            print("=" * 80)
            print(f"Category : {category}")
            print(f"URL      : {url}")

            try:

                # ----------------------------------------------------
                # Open the webpage.
                # ----------------------------------------------------

                await page.goto(
                    url,
                    wait_until="domcontentloaded",
                    timeout=60000
                )

                # ----------------------------------------------------
                # Get the rendered HTML.
                # ----------------------------------------------------

                html = await page.content()

                # ----------------------------------------------------
                # Parse the HTML.
                # ----------------------------------------------------

                soup = BeautifulSoup(html, "html.parser")

                # ----------------------------------------------------
                # Remove tags that never contain useful information.
                # ----------------------------------------------------

                for tag in soup([
                    "script",
                    "style",
                    "noscript",
                    "svg",
                    "iframe",
                    "canvas"
                ]):
                    tag.decompose()

                # ----------------------------------------------------
                # Remove common layout sections.
                # ----------------------------------------------------

                for tag in soup.find_all([
                    "header",
                    "footer",
                    "nav"
                ]):
                    tag.decompose()

                # ----------------------------------------------------
                # Extract visible text.
                # ----------------------------------------------------

                text = soup.get_text(
                    separator="\n",
                    strip=True
                )

                # ----------------------------------------------------
                # Split text into individual lines.
                # ----------------------------------------------------

                lines = text.splitlines()

                # ----------------------------------------------------
                # Remove empty lines.
                # ----------------------------------------------------

                lines = [
                    line.strip()
                    for line in lines
                    if line.strip()
                ]

                # ----------------------------------------------------
                # Remove duplicate lines while preserving order.
                # ----------------------------------------------------

                seen = set()
                cleaned_lines = []

                for line in lines:

                    if line not in seen:

                        cleaned_lines.append(line)
                        seen.add(line)

                # ----------------------------------------------------
                # Remove obvious navigation / UI text.
                # Expand this list as you test more websites.
                # ----------------------------------------------------

                IGNORE = {

                    "About",
                    "Community",
                    "Support",
                    "Newsletter",
                    "Store",
                    "Account",
                    "Contact",
                    "Legal",
                    "Instagram",
                    "YouTube",
                    "TikTok",
                    "Facebook",
                    "LinkedIn",
                    "X",
                    "Privacy",
                    "Cookie Policy",
                    "Terms",
                    "Language",
                    "Country",
                    "Consent Preferences"

                }

                cleaned_lines = [
                    line
                    for line in cleaned_lines
                    if line not in IGNORE
                ]

                # ----------------------------------------------------
                # Join everything back into one string.
                # ----------------------------------------------------

                content = "\n".join(cleaned_lines)

                # ----------------------------------------------------
                # Store the collected page.
                # ----------------------------------------------------

                collected_pages.append(
                    {
                        "company": company,
                        "url": url,
                        "category": category,
                        "content": content
                    }
                )

            except Exception as e:

                print(f"Failed to collect {url}")
                print(e)
                print()

        # ----------------------------------------------------
        # Finished collecting all pages.
        # ----------------------------------------------------

        await browser.close()

        return collected_pages